// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-T-8uew8iAvNzqfBajj-Kkr6Ue1td4vc',
    appId: '1:1000701597699:web:ef9389dbfd4491d7635636',
    messagingSenderId: '1000701597699',
    projectId: 'todoapp-c6f86',
    authDomain: 'todoapp-c6f86.firebaseapp.com',
    storageBucket: 'todoapp-c6f86.firebasestorage.app',
    measurementId: 'G-2W70Y09C0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUW8czyu8udQEXYcCYVnXGDb7xgDNAiC8',
    appId: '1:1000701597699:android:6def33f4e64abac3635636',
    messagingSenderId: '1000701597699',
    projectId: 'todoapp-c6f86',
    storageBucket: 'todoapp-c6f86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHOZOUVj8Q3zoj4ldpSgpzfzqMGv-MpI',
    appId: '1:1000701597699:ios:5634954b1919be9a635636',
    messagingSenderId: '1000701597699',
    projectId: 'todoapp-c6f86',
    storageBucket: 'todoapp-c6f86.firebasestorage.app',
    androidClientId: '1000701597699-9qj5och4ecj9b9ul98ngatfukiuvr9od.apps.googleusercontent.com',
    iosClientId: '1000701597699-vll1ao7eimin4bdqca1ec9n7tqgfp7tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOHOZOUVj8Q3zoj4ldpSgpzfzqMGv-MpI',
    appId: '1:1000701597699:ios:5634954b1919be9a635636',
    messagingSenderId: '1000701597699',
    projectId: 'todoapp-c6f86',
    storageBucket: 'todoapp-c6f86.firebasestorage.app',
    androidClientId: '1000701597699-9qj5och4ecj9b9ul98ngatfukiuvr9od.apps.googleusercontent.com',
    iosClientId: '1000701597699-vll1ao7eimin4bdqca1ec9n7tqgfp7tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-T-8uew8iAvNzqfBajj-Kkr6Ue1td4vc',
    appId: '1:1000701597699:web:9f859bed81157851635636',
    messagingSenderId: '1000701597699',
    projectId: 'todoapp-c6f86',
    authDomain: 'todoapp-c6f86.firebaseapp.com',
    storageBucket: 'todoapp-c6f86.firebasestorage.app',
    measurementId: 'G-79FWGKRVV6',
  );

}