name: settings_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  shared_preferences: ^2.0.15
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
